### ISSUE TITLE
Add GitHub Actions workflow to publish container image to GHCR

### ISSUE THREAD

**Issue by luisalrp** [yctimlin/mcp_excalidraw#8]
Hello 👋,

It would be fantastic to have an automated build-and-publish workflow for this repository’s container image. Publishing to the GitHub Container Registry (GHCR) via GitHub Actions would:

* **Ensure consistency**: Every change to `main` (or a designated branch) triggers a fresh, reproducible image build.
* **Improve discoverability**: Consumers can pull official images with `ghcr.io/<owner>/<repo>:<tag>`.
* **Simplify CI/CD**: Downstream workflows (deployments, tests) can reference a stable, versioned image.

---

### Proposed Workflow

1. **Trigger**

   * On push to `main` (and optionally on tags like `v*.*.*`).
2. **Build**

   * Use `docker/build-push-action` to build the image from the repo’s `Dockerfile`.
3. **Login**

   * Authenticate to GHCR using the built-in `GITHUB_TOKEN`.
4. **Publish**

   * Push the image under `ghcr.io/<owner>/<repo>:${{ github.sha }}` and also tag with the git ref (e.g. `latest`, `v1.2.3`).

```yaml
name: Publish to GHCR

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

permissions:
  packages: write
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.ref_name }}
```

---

### Request

Could we add a workflow like the above to automatically build and publish the container image to GHCR? This will streamline releases and make it easier for users and CI pipelines to consume the latest official images. Thanks! 🎉
